Input improvements
YaccConstructor/Meerkat pull request #38
Opened 2018-05-10 21:59 UTC by darthorimar

Input now is very minimalistic:
```
trait Input[+L, +N] {
  def edgesCount: Int
  def filterEdges(nodeId: Int, predicate: L => Boolean): collection.Seq[(L, Int)]
  def checkNode(nodeId: Int, predicate: N => Boolean): Boolean
}
```
Also, no type magic now

2018-05-11 12:13 UTC, gsvgit requested changes
Всё ещё осталось немного странной магии с типами. Надо доделать.

2018-05-11 12:13 UTC, gsvgit commented on core/src/macros/scala/org/meerkat/Syntax.scala
> +  def syn[L, N, T](p: Parsers.AlternationBuilder[L, N, T]): Nonterminal[L, N] & T= macro makeNonterminalAltWithName[L, N, T]
Обычно V - что-то про тип вершин, E -- что-то про тип рёбер.

2018-05-11 12:13 UTC, gsvgit commented on core/src/main/scala/org/meerkat/parsers/Parsers.scala
> +  def terminal[L, N](l: L): Terminal[L] =
А куда "исчезают" вершины?

2018-05-11 12:13 UTC, gsvgit commented on core/src/main/scala/org/meerkat/parsers/Parsers.scala
> +      if (input.checkNode(i, p))
Т.е. вместо конструирования честной ноды в SPPF для вершины, она фактичесик просто выбрасывается?

2018-05-11 13:08 UTC, darthorimar commented on core/src/macros/scala/org/meerkat/Syntax.scala
> +  def syn[L, N, T](p: Parsers.AlternationBuilder[L, N, T]): Nonterminal[L, N] & T= macro makeNonterminalAltWithName[L, N, T]
Здесь `L` -- тип вершин, `N` -- тип рёбер

2018-05-11 13:08 UTC, darthorimar commented on core/src/main/scala/org/meerkat/parsers/Parsers.scala
> +  def terminal[L, N](l: L): Terminal[L] =
Я Вас не понял

2018-05-11 13:09 UTC, darthorimar commented on core/src/main/scala/org/meerkat/parsers/Parsers.scala
> +      if (input.checkNode(i, p))
Сейчас, да, вершины не сохраняются в SPPF, а используются как фильтры

2018-05-11 13:30 UTC, darthorimar commented on core/src/main/scala/org/meerkat/parsers/Parsers.scala
> +      if (input.checkNode(i, p))
Исправил

2018-05-12 07:53 UTC, gsvgit commented on core/src/macros/scala/org/meerkat/Syntax.scala
> +  def syn[L, N, T](p: Parsers.AlternationBuilder[L, N, T]): Nonterminal[L, N] & T= macro makeNonterminalAltWithName[L, N, T]
Это я понял) И как раз про то, что это как-то "не по людски". Но, я так понимаю, V конфликтует с чем-то уже используемым.

2018-05-12 07:54 UTC, gsvgit commented on core/src/main/scala/org/meerkat/parsers/Parsers.scala
> +  def terminal[L, N](l: L): Terminal[L] =
Это, видимо, к тому, что в SPPF нету соответствующих узлов. Терминаля только для рёбер создаются, если я правильно понимаю то, что здесь происходит.

2018-05-12 07:57 UTC, gsvgit commented on core/src/main/scala/org/meerkat/parsers/Parsers.scala
> +      if (input.checkNode(i, p))
Ок!

2018-05-12 18:33 UTC, darthorimar commented on core/src/main/scala/org/meerkat/parsers/Parsers.scala
> +  def terminal[L, N](l: L): Terminal[L] =
terminal -- функция только для рёбер, да. И у неё есть синоним `E`. Вершины создаются функцией `V`

2018-05-18 12:58 UTC, gsvgit approved these changes

2018-05-18 13:41 UTC, merged